<?php

namespace Ibtikar\ShareEconomyPayFortBundle\Repository;

/**
 * PfPaymentMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PfPaymentMethodRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param  $holder
     * @return integer
     */
    public function hasDefaultPaymentMethod($holder)
    {
        $count = $this->createQueryBuilder('pm')
            ->select('count(pm.id)')
            ->where('pm.holder = :holder')
            ->andWhere('pm.isDefault = :yes')
            ->setParameter('holder', $holder)
            ->setParameter('yes', true)
            ->getQuery()
            ->getSingleScalarResult();

        return $count > 0;
    }
}