<?php

namespace Ibtikar\ShareEconomyPayFortBundle\Repository;

/**
 * PfPaymentMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PfPaymentMethodRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * get latest payment method related to user except the sent one
     *
     * @param \Ibtikar\ShareEconomyPayFortBundle\Entity\PfPaymentMethod $deletedPaymentMethod
     * @return null|\Ibtikar\ShareEconomyPayFortBundle\Entity\PfPaymentMethod
     */
    public function getLatestAddedPaymentMethodExcept($deletedPaymentMethod)
    {
        return $this->createQueryBuilder('pm')
                ->where('pm.holder = :holder')
                ->andWhere('pm.id != :deleted_id')
                ->setParameter('holder', $deletedPaymentMethod->getHolder())
                ->setParameter('deleted_id', $deletedPaymentMethod->getId())
                ->orderBy('pm.id', 'DESC')
                ->setMaxResults(1)
                ->getQuery()
                ->getOneOrNullResult();
    }

    /**
     * @author Mahmoud Mostafa <mahmoud.mostafa@ibtikar.net.sa>
     * @param string $userId
     * @return boolean
     */
    public function clearUserDefaultPaymentMethod($userId)
    {
        return $this->getEntityManager()->createQuery('UPDATE ' . $this->getEntityName() . ' pfp SET pfp.isDefault = 0 WHERE pfp.holder = :userId')->execute(array('userId' => $userId));
    }
}