<?php

namespace Ibtikar\ShareEconomyPayFortBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Ibtikar\ShareEconomyPayFortBundle\Entity\PfTransaction;

/**
 * PfTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PfTransactionRepository extends EntityRepository
{

    /**
     * @return integer
     */
    public function getUpdateStatusCandidatesTransactions()
    {
        return $this->createQueryBuilder('t')
                ->where('t.currentStatus = :pending')
                ->setParameter('pending', PfTransaction::STATUS_PENDING)
                ->getQuery()
                ->execute();
    }

    /**
     * @return integer
     */
    public function getUpdateStatusFailedTransactions()
    {
        return $this->createQueryBuilder('t')
                ->where('t.currentStatus = :fail')
                ->setParameter('fail', PfTransaction::STATUS_FAIL)
                ->getQuery()
                ->execute();
    }
}